# -*- coding: utf-8 -*-
"""eda(week2)6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1680fQjTxRfuAKVHjdZ8nwyyzC0HRtHri
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")

# Monthly bookings
plt.figure(figsize=(8,4))
sns.countplot(data=df, x='arrival_month')
plt.title("Bookings by Arrival Month")
plt.xticks(rotation=45)
plt.show()

# Weekend vs Weekday nights
plt.figure(figsize=(6,4))

nights = {
    "Weekend": df["no_of_weekend_nights"].sum(),
    "Weekday": df["no_of_week_nights"].sum()
}

plt.bar(nights.keys(), nights.values(), color=["skyblue", "orange"])
plt.title("Total Weekend vs Weekday Nights")
plt.show()