# -*- coding: utf-8 -*-
"""EDA(week2)4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UiefKsGovWdkwilUY6_Cf_Qq6ISWKMH3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")
df.head()

def customer_segment(row):
    if row['lead_time'] > 60:
        return "Early Planner"
    elif row['lead_time'] <= 7:
        return "Last-Minute Guest"
    elif row['total_guests'] >= 3:
        return "Family Traveler"
    elif row['market_segment_type'] == "Corporate":
        return "Business Traveler"
    else:
        return "Regular Guest"

df['customer_segment'] = df.apply(customer_segment, axis=1)

df['customer_segment'].value_counts().plot(kind='bar')
plt.title("Customer Segments")
plt.xlabel("Segment")
plt.ylabel("Count")
plt.show()