# -*- coding: utf-8 -*-
"""EDA(week2)2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAEK9TvULTtY6XyKdIYJJcSMtGf2uWRR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")
df.head()

sns.boxplot(x='booking_status', y='lead_time', data=df)
plt.title("Booking Status vs Lead Time")
plt.show()

sns.boxplot(x='booking_status', y='avg_price_per_room', data=df)
plt.title("Booking Status vs Average Room Price")
plt.show()

pd.crosstab(df['room_type_reserved'], df['booking_status']).plot(kind='bar')
plt.title("Booking Status vs Room Type")
plt.xlabel("Room Type")
plt.ylabel("Count")
plt.show()



