# -*- coding: utf-8 -*-
"""EDA(week2)1ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XKsVI0DOFB1Xj32xhDgedaA3q1UMLoE
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")
df.head()

df['booking_status'].value_counts().plot(kind='bar')
plt.title("Booking Status Distribution")
plt.xlabel("Booking Status")
plt.ylabel("Count")
plt.show()

df['market_segment_type'].value_counts().plot(kind='bar')
plt.title("Market Segment Distribution")
plt.xlabel("Market Segment")
plt.ylabel("Count")
plt.show()

df['lead_time'].hist(bins=30)
plt.title("Lead Time Distribution")
plt.xlabel("Lead Time")
plt.ylabel("Frequency")
plt.show()