# -*- coding: utf-8 -*-
"""EDA(week2)5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNZvx8H9plJQP1nWviyg4raBsFsnXpEe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")
df.head()

summary = {
    "Total Bookings": len(df),
    "Cancellation Rate": df['booking_status'].value_counts(normalize=True).get('Canceled', 0) * 100,
    "Average Lead Time": df['lead_time'].mean(),
    "Average Room Price": df['avg_price_per_room'].mean(),
    "Repeat Guest Rate": df['repeated_guest'].mean() * 100
}

for key, value in summary.items():
    print(key, ":", round(value, 2))