# -*- coding: utf-8 -*-
"""EDA(week2)3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6Q1mqhV6wkS4OJz-l6MTlhXwsabWdZb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Hotel_Reservations_EDA_Ready.csv")
df.head()

numeric_df = df.select_dtypes(include=['int64', 'float64'])

plt.figure(figsize=(12, 8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()